import { expect, test } from '@playwright/test'

test('shows the complete finishing route before detailed help on a laptop', async ({ page }) => {
  await page.setViewportSize({ width: 1024, height: 700 })
  await page.goto('/')
  await page.locator('input[type="file"]').first().setInputFiles('tmp/pdfs/mvp-fixture.pdf')
  await expect(page.getByLabel('Rendered PDF page').first()).toBeVisible()
  await page.getByRole('button', { name: 'Document tools', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Help & shortcuts' }).click()
  const help = page.getByRole('complementary', { name: 'Finish and save' })
  const steps = help.locator('.help-steps li')
  await expect(steps).toHaveCount(3)
  for (const step of await steps.all()) await expect(step).toBeInViewport({ ratio: 1 })
  await expect(help.getByText('Shift-click', { exact: false })).toBeVisible()
  await expect(help.locator('details[open]')).toHaveCount(0)
  await page.screenshot({ path: 'output/ui/finishing-guide-1024.png' })

  await help.getByText('Arrange items, pages, and zoom', { exact: true }).click()
  await expect(help.getByText(/Documents open at 100%/)).toBeVisible()
  await expect(help.getByText(/Default zoom follows the screen/)).toHaveCount(0)
  await help.getByRole('button', { name: 'Close finishing help' }).click()
  await expect(help).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Save PDF', exact: true })).toBeEnabled()
})

test('closes the tool panel without swallowing the next action', async ({ page }) => {
  await page.goto('/')
  await page.locator('input[type="file"]').first().setInputFiles('tmp/pdfs/mvp-fixture.pdf')
  await expect(page.getByLabel('Rendered PDF page').first()).toBeVisible()
  const more = page.getByRole('button', { name: 'More editing tools', exact: true })
  await more.click()
  await page.getByRole('button', { name: 'Close editing tools', exact: true }).click()
  await expect(more).toBeFocused()
  await expect(more).toHaveAttribute('aria-expanded', 'false')
  await more.click()
  await page.getByRole('searchbox', { name: 'Find text in document' }).click()
  await expect(more).toHaveAttribute('aria-expanded', 'false')
  await expect(page.getByRole('searchbox', { name: 'Find text in document' })).toBeFocused()
  await more.click()
  await page.getByRole('button', { name: 'Text marks', exact: true }).click()
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('menuitem', { name: 'Underline', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(more).toHaveAttribute('aria-expanded', 'false')
  await expect(more).toBeFocused()
  await expect(more).toHaveClass(/has-active-tool/)
})
